import { customerAddressFields, shippingAddressFields } from './common';
import type { FieldSpec } from './types';
import { header, position } from './types';

/** CMXINV - invoice, 96 fields, one row per line item. */
export const cmxinv: FieldSpec[] = [
	header('recordType', 'C'),
	header('invoiceId', 'I'),
	position('positionNumber', 'I'),
	header('invoiceType', 'I'),
	header('companyId', 'I'),
	header('orderId', 'I'),
	header('customerId', 'I'),
	...customerAddressFields,
	header('invoiceDate', 'D'),
	header('priceDate', 'D'),
	header('paymentCondition', 'I'),
	header('currency', 'C'),
	header('priceGroup', 'I'),
	header('discountGroup', 'I'),
	header('finalDiscount', 'I'),
	header('discountReason', 'C'),
	header('invoiceText', 'C'),
	header('closingText', 'C'),
	header('internalMemo', 'C'),
	header('deleted', 'I'),
	header('language', 'I'),
	header('processor', 'I'),
	header('broker', 'I'),
	header('systemName', 'C'),
	header('status', 'I'),
	header('finalDiscountAmount', 'M'),
	header('finalDiscountAmountReason', 'C'),
	header('shippingType', 'I'),
	header('shippingCosts', 'M'),
	header('cashOnDeliveryFee', 'M'),
	header('serviceDate', 'D'),
	header('deliveryTerms', 'C'),
	header('deliveryTermsAddition', 'C'),
	...shippingAddressFields,
	position('positionType', 'I'),
	position('productId', 'C'),
	position('productDescription', 'C'),
	position('unit', 'C'),
	position('quantity', 'N'),
	position('unitPrice', 'M'),
	position('priceQuantity', 'N'),
	position('positionDiscount', 'M'),
	position('positionValue', 'M'),
	position('productType', 'I'),
	position('taxClassification', 'I'),
	position('taxAlsoAbroad', 'I'),
	position('salesOrderPosition', 'I'),
	position('revenueType', 'I'),
	position('sumOverPosition', 'I'),
	position('revenue', 'M'),
	position('costs', 'M'),
	position('grossProfit', 'M'),
	position('margin', 'M'),
	position('costsManual', 'M'),
	position('gtin', 'C'),
	// Documented as numeric, but exported as a comma separated list of
	// delivery numbers, so it is kept as text.
	position('deliveries', 'C'),
	header('customerOrderNumber', 'C'),
	header('differentRecipient', 'I'),
	header('customerReference', 'C'),
	header('writeProtected', 'I'),
	header('downPaymentPercent', 'I'),
	header('downPaymentAmount', 'M'),
];
