import { customerAddressFields, shippingAddressFields } from './common';
import type { FieldSpec } from './types';
import { header, position } from './types';

/** CMXQTN - quotation, 87 fields, one row per line item. */
export const cmxqtn: FieldSpec[] = [
	header('recordType', 'C'),
	header('quotationId', 'I'),
	position('positionNumber', 'I'),
	header('quotationType', 'I'),
	header('companyId', 'I'),
	header('customerId', 'I'),
	...customerAddressFields,
	header('quotationDate', 'D'),
	header('priceDate', 'D'),
	header('paymentCondition', 'I'),
	header('currency', 'C'),
	header('priceGroup', 'I'),
	header('discountGroup', 'I'),
	header('finalDiscount', 'I'),
	header('discountReason', 'C'),
	header('quotationText', 'C'),
	header('closingText', 'C'),
	header('internalMemo', 'C'),
	header('deleted', 'I'),
	header('rejectedOn', 'D'),
	header('language', 'I'),
	header('processor', 'I'),
	header('broker', 'I'),
	header('finalDiscountAmount', 'M'),
	header('finalDiscountAmountReason', 'C'),
	header('status', 'I'),
	header('deadline', 'D'),
	header('shippingType', 'I'),
	header('shippingCosts', 'M'),
	header('cashOnDeliveryFee', 'M'),
	header('serviceDate', 'D'),
	header('deliveryTerms', 'C'),
	header('deliveryTermsAddition', 'C'),
	...shippingAddressFields,
	position('positionType', 'I'),
	position('productId', 'C'),
	position('productDescription', 'C'),
	position('unit', 'C'),
	position('quantity', 'N'),
	position('unitPrice', 'M'),
	position('priceQuantity', 'N'),
	position('positionDiscount', 'M'),
	position('positionValue', 'M'),
	position('productType', 'I'),
	position('taxClassification', 'I'),
	position('taxAlsoAbroad', 'I'),
	position('revenueType', 'I'),
	position('sumOverPosition', 'I'),
	position('revenue', 'M'),
	position('costs', 'M'),
	position('grossProfit', 'M'),
	position('margin', 'M'),
	position('costsManual', 'M'),
];
